// Login
export const GET_CUSTOMER_PROFILE = 'GET_CUSTOMER_PROFILE';

//Question
export const GET_LIST_GRADE_QUESTION = 'GET_LIST_GRADE_QUESTION';
export const GET_LIST_GROUP_QUESTION = 'GET_LIST_GROUP_QUESTION';
export const GET_LIST_STATUS_QUESTION = 'GET_LIST_STATUS_QUESTION';
export const GET_LIST_SUBJECT_QUESTION = 'GET_LIST_SUBJECT_QUESTION';
export const GET_LIST_CONTENT_QUESTION = 'GET_LIST_CONTENT_QUESTION';
export const GET_LIST_TYPE_QUESTION = 'GET_LIST_TYPE_QUESTION';
export const GET_QUESTION_DETAIL = 'GET_QUESTION_DETAIL';
export const GET_LIST_QUESTION = 'GET_LIST_QUESTION';
export const GET_COUNT_QUESTION = 'GET_COUNT_QUESTION';

//Exam
export const GET_LIST_PUBLIC_EXAM = 'GET_LIST_PUBLIC_EXAM';
export const GET_LIST_SUBJECT_EXAM = 'GET_LIST_SUBJECT_EXAM';
export const GET_LIST_GRADE_EXAM = 'GET_LIST_GRADE_EXAM';
export const GET_LIST_LEVEL_EXAM = 'GET_LIST_LEVEL_EXAM';
export const GET_LIST_STATUS_EXAM = 'GET_LIST_STATUS_EXAM';
export const GET_LIST_STATUS = 'GET_LIST_STATUS';
export const GET_LIST_ALL_QUESTION_EXAM = 'GET_LIST_ALL_QUESTION_EXAM';
export const GET_MY_LIST_EXAM = 'GET_MY_LIST_EXAM';
export const GET_COUNT_LIST_EXAM = 'GET_COUNT_LIST_EXAM';
export const GET_PUBLIC_EXAM_DETAIL = 'GET_PUBLIC_EXAM_DETAIL';
export const GET_LIST_MY_EXAM = 'GET_LIST_MY_EXAM';
export const GET_MY_EXAM_DETAIL = 'GET_MY_EXAM_DETAIL';

// Action Exam
export const GET_EXAM_DETAIL_PREVIEW = 'GET_EXAM_DETAIL_PREVIEW';

// History Exam
export const GET_LIST_HISTORY_EXAM = 'GET_LIST_HISTORY_EXAM';
export const GET_COUNT_HISTORY_EXAM = 'GET_COUNT_HISTORY_EXAM';

//home
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_SINGLE_LIST = 'GET_SINGLE_LIST';
export const GET_LIST_EXAM = 'GET_LIST_EXAM';
export const GET_COUNT_PUBLIC_EXAM = 'GET_COUNT_PUBLIC_EXAM';
